### ISSUE TITLE
updatehub.go: UpgradeToInstallation is not being set after an update

### ISSUE THREAD

**Issue by texierp** [updatehub/updatehub#197]
On the agent start, both validate and rollback states are ignored
when the "UpgradeToInstallation" is < 0). So even if an new installation
is achieved, UpgradeToInstallation is equal to -1, example:

`
...
"update": {
        "download-dir": "/tmp/updatehub",
        "supported-install-modes": [
            "tarball"
        ],
        "upgrade-to-installation": -1
    },
`

**Comment by otavio** [comment]
@texierp are you willing to take a look at this issue?

**Comment by texierp** [comment]
Yes @otavio no problem
