### ISSUE TITLE
Update others SDK to use the Updated API

### ISSUE THREAD

**Issue by Jonathas-Conceicao** [UpdateHub/updatehub#337]
- [x] [agent-sdk-go](https://github.com/UpdateHub/agent-sdk-go)
- [x] [agent-sdk-qt](https://github.com/UpdateHub/agent-sdk-qt)
- [x] [agent-sdk-python](https://github.com/UpdateHub/agent-sdk-python)

**Comment by otavio** [comment]
@Asakiz, we need to update the other SDK accordingly to the changes we did on the Rust one.

**Comment by Jonathas-Conceicao** [comment]
Closing this since those SDK have been updated and standardized.
