### ISSUE TITLE
Idle state being reported when it is not needed

### ISSUE THREAD

**Issue by otavio** [UpdateHub/updatehub#89]
I left the agent running for a while, without a valid server, so we could see how it would handle this case.

I got:

> INFO[3600] Checking update at: /upgrades                                                                 
> INFO[3600] Reporting state: idle                                                                         
> INFO[3600] PackageUID:                                                                                   
> ERRO[3600] failed to report state. HTTP code: 404                                                        
> WARN[3600] Failed to report status                       state=idle                                      

It tried to report the idle state when coming from the probe. This seems wrong as it should report the idle whenever the agent is going to wait for an action (e.g: did not start the download automatically).

**Comment by giulianvivan** [comment]
fixed at 6a06f67b36cff489336b187624ea54714aecfd6a
